### ISSUE TITLE
Crash on x64 Debug builds

### ISSUE THREAD

**Issue by cyanea-bt** [itisluiz/DLLForward#1]
First off thanks for you neat project! Got it working in Release builds of my version.dll without problems (at least from my limited testing so far). But in Debug builds I'm getting a repeatable crash, always on the same lines. Let's start off with some snippets from my dll:

**DllMain**
``` 
BOOL APIENTRY DllMain(HMODULE hModule, DWORD  ul_reason_for_call, LPVOID lpReserved) {
    HANDLE threadHandle;

    switch (ul_reason_for_call)
    {
    case DLL_PROCESS_ATTACH:
        dllforward::setup();
        threadHandle = CreateThread(nullptr, 0, (LPTHREAD_START_ROUTINE)MyThread, hModule, 0, nullptr);
        if (threadHandle) CloseHandle(threadHandle);
        break;
    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
    case DLL_PROCESS_DETACH:
        break;
    }
    return TRUE;
}
```
---
**MyThread**
```
DWORD WINAPI MyThread(HMODULE hModule) {
    FILE* f = nullptr;
    AllocConsole();
    freopen_s(&f, "CONOUT$", "w", stdout);

    // loop
    while (true) {   
        if (GetAsyncKeyState(VK_END) & 1) {
            utils::print("END pressed, exiting!");
            break;
        }

        if (GetAsyncKeyState(VK_F1) & 1) {
            utils::print("F1 pressed, changing value!");
            changeValue();
        }

        Sleep(10);
    }

    // cleanup
    if (f) fclose(f);
    FreeConsole();
    FreeLibraryAndExitThread(hModule, 0);
    return 0;
}
```
---
**changeValue**
```
bool changeValue() {
    // assign some variables
    std::string expectedCode("e9fe4836fc");  <--  ** crash here **
    // assign more variables
    
    modInfo = GetModuleInfo(modHandle);
    auto& [lpBaseOfDll, SizeOfImage, EntryPoint] = modInfo;

    // 3rd argument for scanInternal is type std::string
    aobPtr = scanInternal(static_cast<PCSTR>(lpBaseOfDll), SizeOfImage, "e9fe4836fc");  <-- ** crash here **

   // other stuff
}
```
---
It always crashes on the line that assigns the first std::string. If I remove the string assignments from the start of the function, it will instead crash on the first function call that assigns a string (or at least that's what it looks like to me). And again, these crashes don't happen on Release builds. Also if I change this part of the generated version.h from this:
```
#ifdef _WIN64
		uint8_t opcodes[14]{ 0xFF, 0x25, 0x00, 0x00, 0x00, 0x00 };
		*reinterpret_cast<uintptr_t*>(opcodes + 6) = pProxiedMethod;
#else
		uint8_t opcodes[5]{ 0xE9 };
		*reinterpret_cast<uintptr_t*>(opcodes + 1) = pProxiedMethod - pProxyMethod - sizeof(opcodes);
#endif
```
To just this:
```
                 uint8_t opcodes[5]{ 0xE9 };
		*reinterpret_cast<uintptr_t*>(opcodes + 1) = pProxiedMethod - pProxyMethod - sizeof(opcodes);
```
then the crashes will stop as well. Though on Debug builds I still get a "Run-Time Check Failure #2 - Stack around the variable 'opcodes' was corrupted". But I guess that is to be expected and by just clicking on Ignore, the game will boot right up without issues.

**Comment by itisluiz** [comment]
I'll try to replicate this

**Comment by itisluiz** [comment]
Could [this](https://stackoverflow.com/a/15154074) be your issue? As you're crashing in the std::string constructor, and you're injecting a debug DLL on a process that is otherwise already compiled as release.

**Comment by cyanea-bt** [comment]
Well what is interesting about it is that this crash only started to pop up after using dllforward::setup(). If I remove/don't use DLLForward, then my x64 Debug builds run without issues. Also wouldn't explain why the crashes stop if I simply change the jump instruction for x64 to be the same as x86 (E9...). Or did I miss something on the page you linked?

**Comment by itisluiz** [comment]
I managed to replicate your issue, and I believe I managed to fix it, before commiting anything though I'll do some tests on x86, in the meanwhile, I'd appreciate if you could attempt the following:

In your proxy DLL, replace this:
```cpp
#ifdef _WIN64
		uint8_t opcodes[14]{ 0xFF, 0x25, 0x00, 0x00, 0x00, 0x00 };
		*reinterpret_cast<uintptr_t*>(opcodes + 6) = pProxiedMethod;
#else
		uint8_t opcodes[5]{ 0xE9 };
		*reinterpret_cast<uintptr_t*>(opcodes + 1) = pProxiedMethod - pProxyMethod - sizeof(opcodes);
#endif
```

With this:
```cpp
#ifdef _WIN64
#ifdef _DEBUG
		if (*reinterpret_cast<uint8_t*>(pProxyMethod) == 0xE9)
		{
			int32_t offset{ *reinterpret_cast<int32_t*>(pProxyMethod + 1) };
			pProxyMethod += offset + 5;
		}
#endif
		uint8_t opcodes[14]{ 0xFF, 0x25, 0x00, 0x00, 0x00, 0x00 };
		*reinterpret_cast<uintptr_t*>(opcodes + 6) = pProxiedMethod;
#else
		uint8_t opcodes[5]{ 0xE9 };
		*reinterpret_cast<uintptr_t*>(opcodes + 1) = pProxiedMethod - pProxyMethod - sizeof(opcodes);
#endif
```

To see if it gets fixed for you, and thank you for bringing this up!

**Comment by cyanea-bt** [comment]
Looks good on my end. No warning on startup and no crashes after that either.
